# Generated by Django 2.2.4 on 2019-09-03 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0010_auto_20190903_1519'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hostel_alloted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticeapp.Hostels'),
        ),
        migrations.AddField(
            model_name='profile',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='regno',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sem',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
