# Generated by Django 2.2.4 on 2019-09-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190903_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_students',
            old_name='fullname',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='reg_students',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='reg_students',
            old_name='regno',
            new_name='Regno',
        ),
        migrations.RenameField(
            model_name='reg_students',
            old_name='sem',
            new_name='Sem',
        ),
    ]
