# Generated by Django 2.2.4 on 2019-09-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190904_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isOnline',
        ),
    ]
