# Generated by Django 2.2.3 on 2019-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190905_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_students',
            name='Fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reg_students',
            name='Gender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reg_students',
            name='Regno',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reg_students',
            name='Sem',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
