# Generated by Django 2.2.3 on 2019-09-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0018_auto_20190912_1643'),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='related_hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticeapp.Hostels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Acknowledged'), (2, 'Resolved')], default=0, max_length=1),
        ),
    ]
