# Generated by Django 2.2.3 on 2019-09-12 20:56

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0002_auto_20190912_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=500),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Acknowledged'), ('2', 'Resolved')], max_length=1),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
