# Generated by Django 2.2.4 on 2019-08-29 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=150)),
                ('notice_file', models.FileField(upload_to='Notices')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('val_time', models.DateField()),
                ('concerned_hostels', models.ManyToManyField(to='noticeapp.Hostels')),
            ],
        ),
    ]
