# Generated by Django 2.2.4 on 2019-08-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostels',
            name='Type',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
