# Generated by Django 2.2.4 on 2019-08-29 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0002_hostels_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
