# Generated by Django 2.2.4 on 2019-08-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0003_auto_20190830_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='concerned_hostels',
            field=models.ManyToManyField(blank=True, to='noticeapp.Hostels'),
        ),
    ]
