# Generated by Django 2.2.4 on 2019-08-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0004_auto_20190830_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='val_time',
            field=models.DateField(blank=True),
        ),
    ]
