# Generated by Django 2.2.4 on 2019-08-29 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0005_auto_20190830_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='concerned_hostels',
            field=models.ManyToManyField(blank=True, null=True, to='noticeapp.Hostels'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='val_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
