# Generated by Django 2.2.4 on 2019-08-29 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0007_auto_20190830_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='concerned_hostels',
            field=models.ManyToManyField(to='noticeapp.Hostels'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=models.TextField(default="abc", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notices',
            name='label',
            field=models.CharField(default="abc", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(default="abc", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notices',
            name='val_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
