# Generated by Django 2.2.4 on 2019-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0009_auto_20190830_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_file',
            field=models.FileField(upload_to='Notices'),
        ),
    ]
