# Generated by Django 2.2.4 on 2019-09-05 22:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0010_auto_20190903_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='concerned_hostels',
            field=models.ManyToManyField(to='noticeapp.Hostels'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=150),
        ),
    ]
