# Generated by Django 2.2.4 on 2019-09-08 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0011_auto_20190906_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='val_time',
            field=models.DateField(blank=True),
        ),
    ]
