# Generated by Django 2.2.4 on 2019-09-08 20:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0012_auto_20190909_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='notices',
            name='label',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
