# Generated by Django 2.2.4 on 2019-09-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0013_auto_20190909_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='val_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
