# Generated by Django 2.2.3 on 2019-09-11 19:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0014_auto_20190909_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefWardens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('contact', models.CharField(max_length=15)),
                ('hostel_type', models.CharField(choices=[('1', 'Boys'), ('2', 'Girls')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='General_Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hostels',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='notices',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='notices',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notices',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Hostel_Management_Commitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warden_email', models.CharField(max_length=50)),
                ('care_taker_email', models.CharField(max_length=50)),
                ('hostel_president_email', models.CharField(blank=True, max_length=50)),
                ('hostel_manager_email', models.CharField(blank=True, max_length=50)),
                ('hostel_secretary_email', models.CharField(blank=True, max_length=50)),
                ('chief_warden_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeapp.ChiefWardens')),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noticeapp.Hostels')),
            ],
        ),
    ]
