# Generated by Django 2.2.3 on 2019-09-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0015_auto_20190912_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_authority',
            name='designations',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
