# Generated by Django 2.2.3 on 2019-09-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0016_general_authority_designations'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='issuing_authority',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
