# Generated by Django 2.2.3 on 2019-09-12 20:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeapp', '0018_auto_20190912_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=150),
        ),
    ]
